In [3]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.10.0+cpu


Introduction TO Tensor
Creating Tensors


In [4]:
1 # Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get Tensor Back as Python Int
scalar.item()


7

In [7]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
mx = torch.tensor([[7,8],
                   [9,10]])
mx.ndim

2

In [11]:
mx[1]

tensor([ 9, 10])

In [12]:
mx.shape

torch.Size([2, 2])

In [13]:
# TENSOR 
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 4, 5]])

 Random Tensors
 
 Why Random Tensors?

 Random tensors are important the way many neural networks learn is that they start with tensors full of random numbers 
 and then adjust those random numbers to bettter represent the data.

 ' Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [17]:
 # Creating a Random tennsor of size(3,4)
 
rdm_tnsr =torch.rand(3,4)
rdm_tnsr
 

tensor([[0.6008, 0.4693, 0.5565, 0.7847],
        [0.0318, 0.4563, 0.2241, 0.7521],
        [0.6332, 0.7436, 0.2402, 0.7552]])

In [18]:
rdm_tnsr.ndim

2

In [19]:
# Create a random tensor woth similar shape to an image tensor

rdm_img_size_tnsr = torch.rand(size=(224,224,3)) # height, width, color channels
rdm_img_size_tnsr.shape, rdm_img_size_tnsr.ndim 

(torch.Size([224, 224, 3]), 3)

Zeros and Ones :


In [20]:
# Creates a Tensor of all Zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*rdm_tnsr

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a Tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
rdm_tnsr.dtype

torch.float32

Creating a Range of Tensors and Tensors-like :-

In [ ]:
# Use torch.range() and get deprecated message ,use torch.arrage()
torch.range(0,10)

C:\Users\ajayr\AppData\Local\Temp\ipykernel_11784\3858421243.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
torch.__version__

'2.10.0+cpu'

In [27]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [28]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors Like
tn_gros =torch.zeros_like(input=one_to_ten)
tn_gros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor DataTypes :

Note: Tensor datatypes is one of the " 3 Big Errors " you'll run into PyTorch and Deeplearnig
1. Tensors not right datatypes
2. Tensor not right shape
3. Tensor not on the right device

In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,  # what  datatype is the tensor (ex,float32 or float16) 
                               device=None,  # what is your tensor on
                               requires_grad=False) # whether or not to track grandients with this tensors operations
float_32_tensor



tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor =float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [39]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [40]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors ( Tensor Attributes)

1. Tensors not right datatypes -to do get datatype from a tensor ,can use 'tensor.dtype'
2. Tensor not right shape - to get shape from a tensor , can use 'tensor.shape'
3. Tensor not on the right device - to get device from a tensor ,can use 'tensor.device'


In [42]:
# Creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1003, 0.0094, 0.4033, 0.5807],
        [0.9248, 0.3211, 0.8915, 0.7879],
        [0.1473, 0.8339, 0.0609, 0.1248]])

In [44]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [45]:
some_tensor.size()

torch.Size([3, 4])

In [46]:
# Fing=d out details about some tensor 
print(some_tensor)
print(f"Datatypes of tensor : {some_tensor.dtype} ")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.1003, 0.0094, 0.4033, 0.5807],
        [0.9248, 0.3211, 0.8915, 0.7879],
        [0.1473, 0.8339, 0.0609, 0.1248]])
Datatypes of tensor : torch.float32 
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu
