In [1]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.10.0+cpu


Introduction TO Tensor
Creating Tensors


In [2]:
1 # Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get Tensor Back as Python Int
scalar.item()


7

In [5]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
mx = torch.tensor([[7,8],
                   [9,10]])
mx.ndim

2

In [9]:
mx[1]

tensor([ 9, 10])

In [10]:
mx.shape

torch.Size([2, 2])

In [11]:
# TENSOR 
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 4, 5]])

 Random Tensors
 
 Why Random Tensors?

 Random tensors are important the way many neural networks learn is that they start with tensors full of random numbers 
 and then adjust those random numbers to bettter represent the data.

 ' Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [15]:
 # Creating a Random tennsor of size(3,4)
 
rdm_tnsr =torch.rand(3,4)
rdm_tnsr
 

tensor([[0.4233, 0.0082, 0.3489, 0.0370],
        [0.1091, 0.7496, 0.2887, 0.1016],
        [0.5099, 0.7975, 0.9274, 0.0687]])

In [16]:
rdm_tnsr.ndim

2

In [17]:
# Create a random tensor woth similar shape to an image tensor

rdm_img_size_tnsr = torch.rand(size=(224,224,3)) # height, width, color channels
rdm_img_size_tnsr.shape, rdm_img_size_tnsr.ndim 

(torch.Size([224, 224, 3]), 3)

Zeros and Ones :


In [18]:
# Creates a Tensor of all Zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*rdm_tnsr

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a Tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
rdm_tnsr.dtype

torch.float32

Creating a Range of Tensors and Tensors-like :-

In [23]:
# Use torch.range() and get deprecated message ,use torch.arrage()
torch.range(0,10)

C:\Users\ajayr\AppData\Local\Temp\ipykernel_23608\2703403991.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
torch.__version__

'2.10.0+cpu'

In [25]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors Like
tn_gros =torch.zeros_like(input=one_to_ten)
tn_gros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor DataTypes :

Note: Tensor datatypes is one of the " 3 Big Errors " you'll run into PyTorch and Deeplearnig
1. Tensors not right datatypes
2. Tensor not right shape
3. Tensor not on the right device

In [28]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,  # what  datatype is the tensor (ex,float32 or float16) 
                               device=None,  # what is your tensor on
                               requires_grad=False) # whether or not to track grandients with this tensors operations
float_32_tensor



tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor =float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors ( Tensor Attributes)

1. Tensors not right datatypes -to do get datatype from a tensor ,can use 'tensor.dtype'
2. Tensor not right shape - to get shape from a tensor , can use 'tensor.shape'
3. Tensor not on the right device - to get device from a tensor ,can use 'tensor.device'


In [34]:
# Creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7090, 0.5087, 0.5126, 0.8693],
        [0.3052, 0.7034, 0.3489, 0.9104],
        [0.8791, 0.7914, 0.8202, 0.7569]])

In [35]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [36]:
some_tensor.size()

torch.Size([3, 4])

In [37]:
# Fing=d out details about some tensor 
print(some_tensor)
print(f"Datatypes of tensor : {some_tensor.dtype} ")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.7090, 0.5087, 0.5126, 0.8693],
        [0.3052, 0.7034, 0.3489, 0.9104],
        [0.8791, 0.7914, 0.8202, 0.7569]])
Datatypes of tensor : torch.float32 
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors ( Tensor Operations) :
Tensor Operations Includes :
1. Addition
2. Subtraction
3. Multiplication( Element-Wise)
4.Division
5. Matrix multiplication

In [38]:
# Creating a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [40]:
tensor

tensor([1, 2, 3])

In [41]:
# Suntract 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
# try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [44]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

###  Matrix Multiplication 
Two main ways of performing multiplication in neural networks and deep learning :
1.Elements wise multipliaction 
2.Matrix multiplication (dot product)

more information on multiply matrics -https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are  two main that perform matrix multiplication needs to satisfy:
1. the **inner dimensions ** must match:
* '(3,2) @ ( 3,2)' wont't work
*'(2,3) @ (3,2)' will work
* '(3,2) @  (2,3)' will work

2. The resulting matrix has the shape of the ** outer dimensions ** :
*  '(2,3 ) @  (3,2)' -> (2,2)
* '(3,2) @ (2,3)' -> (3,3)



In [45]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10)).shape

torch.Size([10, 10])

In [46]:
# Elements  wise multiplication
print(tensor , "*", tensor)
print(f"Equals : {tensor * tensor }")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [47]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [48]:
# Matrix multiplication on hand
1*1 + 2*2 + 3*3

14

In [49]:
tensor @ tensor 

tensor(14)

In [50]:
%%time
value =0
for i in range (len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 6.01 ms


In [51]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 441 μs


tensor(14)

### One of the common error in Deep Learning shape errors :


In [53]:
# Shape for matrix multipliaction 
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul(it's an alis for)
torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [54]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulates the one of our tensor using a **transpose**.

A **transpose** switches  the axes or dimensions of a given tensor.

In [55]:
tensor_B.T, 

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),)

In [56]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [57]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [58]:
# The Matix multiplication operation works when tensor_B is transposed:
print(f"Original shape : tensor_A = {tensor_A.shape}, tensor_B ={tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape } @ {tensor_B.T.shape} <- innetr dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}") 



Original shape : tensor_A = torch.Size([3, 2]), tensor_B =torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- innetr dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min,max,mean,sum, etc(tensor aggregation) 

In [59]:
# Create a tensor
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [62]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note : the torch.mean() function required a tensor of float32 data type to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [66]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the position min and max:

In [67]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -->return index positions of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [69]:
x[0]

tensor(0)

In [70]:
# Find the position in that has the maximum value with argmax()
x.argmax()

tensor(9)

In [71]:
x[9]

tensor(90)

## Reshaping, Stacking, Squeezing and unsqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory  as the original tensor
* Stacking - combine multiple tensors on top each other (vstack) or side by side (hstack)
* Squeez - remove all '1' dimension from a tensor
* Unsqueez - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [72]:
# Lets create a tensor 
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [74]:
# Add an extra dimensions
x_reshaped =x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
# Add an extra dimensions
x_reshaped =x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [76]:
# change  the view 
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
# Changing z changes x (becaues a view of a tensor shares the same memory as the original input)
z[:, 0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [79]:
# Stack tensors on top of each other
x_stacked  = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [80]:
# Stack tensors on top of each other
x_stacked  = torch.stack([x, x, x, x], dim=1)
x_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])