NumPY Functons :

In [1]:
import numpy as np

arange()

In [3]:
# np.arange(star,Ende,steps)

ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
evn_ar = np.arange(1,13,2)
print(evn_ar)

[ 1  3  5  7  9 11]


linspace()

In [5]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

reshape()

In [7]:
ar_2d =ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
ar_23d=ar_1d.reshape(2,3,2)
print(ar_23d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
arn=np.arange(1,13).reshape(2,6)
print(arn)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


ravel()
Ravel is converted multi dimensional array into 1d array


In [10]:
arn.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

flatten()--> same as it work ravel funtion

In [ ]:
arn.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

transpose()-->row is converted into columns

In [12]:
arn.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])