Random Sampling With NumPy :

In [1]:
import numpy as np
import random 

In [2]:
np.random.random(1)

array([0.72342923])

In [4]:
np.random.random((3,3))

array([[0.07102342, 0.95813196, 0.06178571],
       [0.09412315, 0.33477702, 0.93561803],
       [0.29209356, 0.28887288, 0.85396422]])

In [5]:
np.random.randint(1,4)

2

In [6]:
np.random.randint(1,4, (4,4))

array([[2, 1, 1, 2],
       [2, 3, 3, 3],
       [2, 2, 2, 1],
       [1, 1, 3, 2]], dtype=int32)

In [7]:
np.random.randint(1,4, (2,4,4))

array([[[2, 1, 2, 2],
        [2, 3, 1, 1],
        [1, 2, 2, 1],
        [1, 3, 3, 3]],

       [[3, 2, 1, 2],
        [3, 2, 3, 1],
        [1, 2, 2, 1],
        [3, 2, 2, 3]]], dtype=int32)

In [8]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]], dtype=int32)

In [10]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]], dtype=int32)

In [11]:
2**32 -1

4294967295

In [12]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [13]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [16]:
x = [1,2,3,4]
np.random.choice(x)

np.int64(4)

In [17]:
np.random.choice(x)

np.int64(1)

In [18]:
np.random.choice(x)

np.int64(3)

In [20]:
for i in range(20):
   print( np.random.choice(x))

2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3


In [21]:
x

[1, 2, 3, 4]

In [22]:
np.random.permutation(x)

array([2, 3, 1, 4])

In [23]:
np.random.permutation(x)

array([2, 3, 4, 1])